version: 0.0
os: linux
files:
  - source: ./target/pinoypoetry-1.0.0.war
    destination: /appl
hooks:
  ApplicationStop:
    - location: ./scripts/stop.sh
      timeout: 400
  ApplicationStart:
    - location: ./scripts/start.sh
      timeout: 300