version: 0.0
os: linux
files:
  - source: ./target/pinoypoetry-1.0.1.war
    destination: /appl
hooks:
  ApplicationStop:
    - location: scripts/stop_please.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300