version: 0.2
phases:
  pre_build:
    commands:
      - mvn dependency:resolve
  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - target/pinoypoetry-0.0.1.jar
    - appspec.yml
    - scripts/start.sh
