version: 0.2
phases:
  build:
    commands:
      - mvn clean package

artifacts:
  files:
    - target/pinoypoetry-1.0.1.war
    - appspec.yml
    - scripts/stop_please.sh
    - scripts/start.sh
cache:
  paths:
  - '/root/.m2/**/*'